import type { Incident } from '../types/incident';
import type { Alert } from '../types/alert';
import type { AnalyticsOverview } from '../types/analytics';
import type { SystemStatus, KPIMetrics } from '../types/system';

export const mockKPIMetrics: KPIMetrics = {
  total_thermal_anomalies: 1428,
  active_incidents: 34,
  critical_risk_incidents: 8,
  industrial_incidents: 18,
  wildfire_incidents: 11,
  persistent_heat_sources: 15,
};

export const mockSystemStatus: SystemStatus = {
  system_status: 'operational',
  satellite_feeds: {
    MODIS: 'active',
    VIIRS: 'active',
    SENTINEL3: 'active',
  },
  last_telemetry_sync: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  active_nodes: 12,
  ai_model_version: 'v2.4-thermal-sentinel',
  active_alerts_count: 6,
};

export const mockIncidents: Incident[] = [
  {
    id: 'INC-2026-089',
    title: 'High Thermal Radiance in North Ridge Sector',
    location: {
      name: 'North Ridge Forestry Reserve, Zone B',
      lat: 34.0522,
      lng: -118.2437,
      region: 'Northern Sector',
    },
    event_type: 'wildfire',
    confidence: 96.5,
    risk_score: 94.0,
    severity: 'critical',
    status: 'active',
    temperature_kelvin: 720.5,
    frp_mw: 185.4,
    detected_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    satellite_source: 'VIIRS',
    historical_anomaly_count: 2,
    is_persistent: false,
    description: 'Rapidly expanding thermal footprint detected in dense pine vegetation canopy. High wind velocity detected in region.',
    recommended_actions: [
      'Dispatch aerial thermal surveillance drone',
      'Issue immediate warning to local forestry stations',
      'Mobilize ground suppression unit 4',
    ],
  },
  {
    id: 'INC-2026-088',
    title: 'Unscheduled Heat Flare - Refinery Complex 7',
    location: {
      name: 'Industrial Zone West, Bay 4',
      lat: 29.9511,
      lng: -90.0715,
      region: 'Gulf Industrial Belt',
    },
    event_type: 'flare_stack',
    confidence: 99.1,
    risk_score: 88.5,
    severity: 'critical',
    status: 'investigating',
    temperature_kelvin: 890.0,
    frp_mw: 310.2,
    detected_at: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    satellite_source: 'MODIS',
    historical_anomaly_count: 48,
    is_persistent: true,
    description: 'Refinery flare stack thermal output exceeds baseline permitted thresholds by 240%. AI assessment indicates potential pressure relief vent blowout.',
    recommended_actions: [
      'Contact site safety engineer immediately',
      'Verify automatic emergency shut-off valves',
      'Monitor air quality sensor grid downwind',
    ],
  },
  {
    id: 'INC-2026-087',
    title: 'Sub-Canopy Thermal Anomaly - Eastern Hills',
    location: {
      name: 'Eastern Hills Wildlife Corridor',
      lat: 37.7749,
      lng: -122.4194,
      region: 'Central Uplands',
    },
    event_type: 'wildfire',
    confidence: 88.2,
    risk_score: 79.4,
    severity: 'high',
    status: 'active',
    temperature_kelvin: 610.8,
    frp_mw: 92.6,
    detected_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    satellite_source: 'SENTINEL3',
    historical_anomaly_count: 0,
    is_persistent: false,
    description: 'Cluster of hot spots expanding along steep terrain gradient. Potential lightning strike origin.',
    recommended_actions: [
      'Deploy lookout tower optics',
      'Check local weather station lightning logs',
    ],
  },
  {
    id: 'INC-2026-086',
    title: 'Steel Mill Secondary Furnace Emission Spike',
    location: {
      name: 'AeroMet Metals Plant, District 12',
      lat: 41.8781,
      lng: -87.6298,
      region: 'Midwest Manufacturing Center',
    },
    event_type: 'industrial',
    confidence: 95.0,
    risk_score: 72.1,
    severity: 'high',
    status: 'contained',
    temperature_kelvin: 940.3,
    frp_mw: 245.0,
    detected_at: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    satellite_source: 'AI_FUSION',
    historical_anomaly_count: 120,
    is_persistent: true,
    description: 'High radiance point source corresponding to slag pouring operations. Slightly elevated temperature offset.',
    recommended_actions: [
      'Log as expected industrial operating cycle',
      'Re-evaluate baseline threshold for District 12',
    ],
  },
  {
    id: 'INC-2026-085',
    title: 'Agricultural Stubble Burning Cluster',
    location: {
      name: 'Valley Farmlands Sector 9',
      lat: 36.7783,
      lng: -119.4179,
      region: 'Agricultural Basin',
    },
    event_type: 'agricultural',
    confidence: 84.7,
    risk_score: 55.0,
    severity: 'medium',
    status: 'investigating',
    temperature_kelvin: 520.4,
    frp_mw: 42.1,
    detected_at: new Date(Date.now() - 210 * 60 * 1000).toISOString(),
    satellite_source: 'VIIRS',
    historical_anomaly_count: 14,
    is_persistent: false,
    description: 'Multiple low-intensity thermal anomalies detected across crop harvest plots.',
    recommended_actions: [
      'Cross-reference seasonal burning permits',
      'Notify regional agricultural burn inspector',
    ],
  },
  {
    id: 'INC-2026-084',
    title: 'Urban Surface Heat Retention Anomaly',
    location: {
      name: 'Metro Center Plaza & Roof Grid',
      lat: 40.7128,
      lng: -74.0060,
      region: 'Eastern Megacity',
    },
    event_type: 'urban_heat',
    confidence: 79.5,
    risk_score: 41.2,
    severity: 'low',
    status: 'resolved',
    temperature_kelvin: 318.6,
    frp_mw: 12.0,
    detected_at: new Date(Date.now() - 320 * 60 * 1000).toISOString(),
    satellite_source: 'MODIS',
    historical_anomaly_count: 310,
    is_persistent: true,
    description: 'Solar radiation absorption by dark asphalt roofing materials during heatwave peak.',
    recommended_actions: [
      'No emergency action required',
      'Record solar heat island baseline metrics',
    ],
  },
  {
    id: 'INC-2026-083',
    title: 'Unidentified Thermal Spike - Deep Woodland',
    location: {
      name: 'Pine Valley Wilderness, Parcel 8',
      lat: 44.0682,
      lng: -121.3153,
      region: 'Northwest Forest',
    },
    event_type: 'unknown',
    confidence: 71.0,
    risk_score: 68.3,
    severity: 'medium',
    status: 'active',
    temperature_kelvin: 540.1,
    frp_mw: 58.9,
    detected_at: new Date(Date.now() - 390 * 60 * 1000).toISOString(),
    satellite_source: 'SENTINEL3',
    historical_anomaly_count: 0,
    is_persistent: false,
    description: 'Isolated thermal hotspot detected remote from known structures or industrial activity.',
    recommended_actions: [
      'Task high-resolution satellite re-pass',
      'Verify citizen emergency calls in vicinity',
    ],
  },
  {
    id: 'INC-2026-082',
    title: 'Chemical Plant Storage Tank Thermal Signature',
    location: {
      name: 'ChemTech Logistics Hub, Tank 14',
      lat: 32.7767,
      lng: -96.7970,
      region: 'Southwest Hub',
    },
    event_type: 'industrial',
    confidence: 97.8,
    risk_score: 91.5,
    severity: 'critical',
    status: 'active',
    temperature_kelvin: 760.4,
    frp_mw: 215.3,
    detected_at: new Date(Date.now() - 480 * 60 * 1000).toISOString(),
    satellite_source: 'AI_FUSION',
    historical_anomaly_count: 1,
    is_persistent: false,
    description: 'Thermal anomaly detected on pressurized chemical solvent tank wall. Exothermic reaction suspected.',
    recommended_actions: [
      'Initiate emergency site evacuation protocol',
      'Activate automated fire suppression water deluge',
      'Notify hazardous materials containment squad',
    ],
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-9045',
    incident_id: 'INC-2026-089',
    alert_type: 'critical_incident',
    title: 'CRITICAL: Rapid Canopy Fire Spread',
    location: 'North Ridge Forestry Reserve, Zone B',
    severity: 'critical',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    reason: 'FRP exceeded 180MW threshold. High rate of perimeter expansion.',
    status: 'unacknowledged',
  },
  {
    id: 'ALT-9044',
    incident_id: 'INC-2026-082',
    alert_type: 'critical_incident',
    title: 'HAZMAT CRITICAL: Exothermic Tank Elevation',
    location: 'ChemTech Logistics Hub, Tank 14',
    severity: 'critical',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    reason: 'AI classification flagged unexpected solvent heating profile.',
    status: 'investigating',
  },
  {
    id: 'ALT-9043',
    incident_id: 'INC-2026-088',
    alert_type: 'high_risk',
    title: 'HIGH RISK: Unplanned Refinery Flare Flare-up',
    location: 'Industrial Zone West, Bay 4',
    severity: 'critical',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    reason: 'Radiance 240% above baseline historical maximum.',
    status: 'acknowledged',
  },
  {
    id: 'ALT-9042',
    alert_type: 'citizen_report',
    title: 'CITIZEN REPORT: Smoke Plume & Burning Smell',
    location: 'Pine Valley Community Edge',
    severity: 'high',
    timestamp: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    reason: 'Multiple 911 calls verified by spatial correlation engine.',
    status: 'unacknowledged',
    reporter_info: 'Verified via Emergency Dispatch API',
  },
  {
    id: 'ALT-9041',
    incident_id: 'INC-2026-087',
    alert_type: 'abnormal_event',
    title: 'ABNORMAL: Off-Season Vegetation Heat',
    location: 'Eastern Hills Wildlife Corridor',
    severity: 'high',
    timestamp: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    reason: 'Thermal anomaly detected in area with 0 historical heat records.',
    status: 'investigating',
  },
  {
    id: 'ALT-9040',
    incident_id: 'INC-2026-085',
    alert_type: 'abnormal_event',
    title: 'PERMIT MISMATCH: Unregistered Agricultural Fire',
    location: 'Valley Farmlands Sector 9',
    severity: 'medium',
    timestamp: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    reason: 'Active burn location does not align with registered permit zone.',
    status: 'resolved',
  },
];

export const mockAnalyticsOverview: AnalyticsOverview = {
  anomalies_over_time: [
    { timestamp: '00:00', anomalies: 42, critical: 2, industrial: 28, wildfire: 12 },
    { timestamp: '03:00', anomalies: 35, critical: 1, industrial: 25, wildfire: 9 },
    { timestamp: '06:00', anomalies: 58, critical: 3, industrial: 32, wildfire: 23 },
    { timestamp: '09:00', anomalies: 94, critical: 6, industrial: 48, wildfire: 40 },
    { timestamp: '12:00', anomalies: 142, critical: 8, industrial: 65, wildfire: 69 },
    { timestamp: '15:00', anomalies: 128, critical: 7, industrial: 58, wildfire: 63 },
    { timestamp: '18:00', anomalies: 98, critical: 4, industrial: 45, wildfire: 49 },
    { timestamp: '21:00', anomalies: 64, critical: 2, industrial: 38, wildfire: 24 },
  ],
  event_category_distribution: [
    { category: 'Industrial Heat', count: 482, percentage: 33.8, color: '#3b82f6' },
    { category: 'Wildfire / Forest', count: 395, percentage: 27.6, color: '#ef4444' },
    { category: 'Flare Stacks', count: 264, percentage: 18.5, color: '#f97316' },
    { category: 'Urban Heat Island', count: 185, percentage: 12.9, color: '#a855f7' },
    { category: 'Agricultural Burning', count: 102, percentage: 7.2, color: '#eab308' },
  ],
  risk_level_distribution: [
    { level: 'Critical Risk', count: 8, color: '#ef4444' },
    { level: 'High Risk', count: 26, color: '#f97316' },
    { level: 'Medium Risk', count: 68, color: '#eab308' },
    { level: 'Low Risk', count: 1326, color: '#10b981' },
  ],
  persistent_vs_sudden: [
    { type: 'Persistent Heat Sources', count: 312, description: 'Monitored refineries, steel mills & industrial stacks' },
    { type: 'Sudden Heat Outbursts', count: 1116, description: 'Unpredicted thermal anomalies requiring rapid triage' },
  ],
  industrial_vs_natural: [
    { month: 'Jan', industrial: 210, natural: 65, agricultural: 25 },
    { month: 'Feb', industrial: 205, natural: 58, agricultural: 30 },
    { month: 'Mar', industrial: 225, natural: 82, agricultural: 45 },
    { month: 'Apr', industrial: 240, natural: 110, agricultural: 95 },
    { month: 'May', industrial: 255, natural: 180, agricultural: 140 },
    { month: 'Jun', industrial: 260, natural: 320, agricultural: 110 },
    { month: 'Jul', industrial: 270, natural: 480, agricultural: 85 },
    { month: 'Aug', industrial: 265, natural: 420, agricultural: 70 },
  ],
};
